/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.*;

/**
 *
 * @author IBRAHIM
 */
public class Pesanan extends javax.swing.JFrame {
    
    public DefaultTableModel model;
    public String nom;
    int cellBaris;
    /**
     * Creates new form Pesanan
     */
    public Pesanan() {
        initComponents();
        pesananNih();
        String[] headerTabel = {"Nomor Pemesanan", "Nama Buku", "Status Pembayaran", "Jumlah Harga"};
        model = new DefaultTableModel(headerTabel, 0);
        tablePesanan.setModel(model);
        nomor.setVisible(false);
        
        rekBank.setEditable(false);
        kodPes.setEditable(false);
        
        Toolkit tlkit = getToolkit();
        Dimension size = tlkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, size.height/2 - getHeight()/2);   
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePesanan = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        hapusPesanan = new javax.swing.JButton();
        pesananTermehong = new javax.swing.JButton();
        belumBayar = new javax.swing.JButton();
        home = new javax.swing.JButton();
        nomor = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pilihB = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        rekBank = new javax.swing.JTextField();
        kodPes = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        kPembayaran = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        pesananTermurah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Toko Buku Jawir");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Poppins SemiBold", 1, 14)); // NOI18N
        jLabel1.setText("Daftar Pesanan");

        tablePesanan.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        tablePesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablePesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePesanan);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/icon/book (2).png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        jLabel3.setText("Toko Buku Jawir");

        hapusPesanan.setBackground(new java.awt.Color(255, 0, 0));
        hapusPesanan.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        hapusPesanan.setForeground(new java.awt.Color(255, 255, 255));
        hapusPesanan.setText("Batalkan Pesanan");
        hapusPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPesananActionPerformed(evt);
            }
        });

        pesananTermehong.setBackground(new java.awt.Color(255, 136, 51));
        pesananTermehong.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        pesananTermehong.setForeground(new java.awt.Color(255, 255, 255));
        pesananTermehong.setText("Pesanan termahal");
        pesananTermehong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesananTermehongActionPerformed(evt);
            }
        });

        belumBayar.setBackground(new java.awt.Color(102, 153, 255));
        belumBayar.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        belumBayar.setForeground(new java.awt.Color(255, 255, 255));
        belumBayar.setText("Belum dibayar");
        belumBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                belumBayarActionPerformed(evt);
            }
        });

        home.setBackground(new java.awt.Color(0, 0, 204));
        home.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        home.setForeground(new java.awt.Color(255, 255, 255));
        home.setText("Daftar buku");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        nomor.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        nomor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 136, 51)));

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Tampil Pesanan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel5.setText("Pembayaran");

        jLabel6.setFont(new java.awt.Font("Montserrat SemiBold", 0, 12)); // NOI18N
        jLabel6.setText("Pilih Metode Pembayaran");

        pilihB.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        pilihB.setForeground(new java.awt.Color(255, 153, 0));
        pilihB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bank Mandiri", "Bank BNI", "Bank BRI", "Bank BCA" }));
        pilihB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        pilihB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihBActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Rekening Pembayaran");

        rekBank.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        rekBank.setForeground(new java.awt.Color(255, 102, 51));
        rekBank.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rekBank.setBorder(null);

        kodPes.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        kodPes.setForeground(new java.awt.Color(255, 51, 0));
        kodPes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        kodPes.setBorder(null);

        jLabel8.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Kode Pesanan");

        jLabel9.setFont(new java.awt.Font("Poppins SemiBold", 2, 8)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("(*Gunakan rekening pembayaran untuk membayar pesananmu di bawah");

        kPembayaran.setBackground(new java.awt.Color(0, 204, 51));
        kPembayaran.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
        kPembayaran.setForeground(new java.awt.Color(255, 255, 255));
        kPembayaran.setText("Konfirmasi Pembayaran");
        kPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kPembayaranActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Poppins SemiBold", 2, 8)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("(*Jika sudah melakukan pembayaran klik konfirmasi pembayaran");

        pesananTermurah.setBackground(new java.awt.Color(0, 204, 204));
        pesananTermurah.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        pesananTermurah.setForeground(new java.awt.Color(255, 255, 255));
        pesananTermurah.setText("Pesanan termurah");
        pesananTermurah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesananTermurahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(belumBayar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pesananTermehong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pesananTermurah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hapusPesanan))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(279, 279, 279))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(rekBank, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kodPes, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(kPembayaran)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nomor, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pilihB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(195, 195, 195))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(nomor, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pilihB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(208, 208, 208)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rekBank, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kodPes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel10)
                                .addGap(87, 87, 87)
                                .addComponent(kPembayaran)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(pesananTermehong, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(belumBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pesananTermurah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(home)
                        .addGap(562, 562, 562)
                        .addComponent(hapusPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        nom = nomor.getText(); // Mengambil teks dari textfield
        model.setRowCount(0);

        // Mengecek apakah salah satu kosong atau tidak jika ya menampilkan window error
        if(nom.isEmpty()){
            JOptionPane.showMessageDialog(this, "Isi nomor telepon", "Error", JOptionPane.ERROR_MESSAGE);
            model.setRowCount(0);
        }else{
            tampilPesanan(nom);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        Dashboard dbrd = new Dashboard();
        dbrd.setVisible(true);
        setVisible(false);
        dbrd.no.setText(nomor.getText());
        
    }//GEN-LAST:event_homeActionPerformed

    private void belumBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_belumBayarActionPerformed
        // TODO add your handling code here:

        nom = nomor.getText();
        model.setRowCount(0);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection cnc = DriverManager.getConnection("jdbc:mysql://localhost:3306/uas", "root", "");
            String cmd_sql = "SELECT id_pesanan, buku.nama_buku, status, harga_pesanan FROM pesanan INNER JOIN buku ON pesanan.id_buku = buku.id_buku WHERE status = \"Belum dibayar\" AND id_keranjang = ?";
            PreparedStatement stm = cnc.prepareStatement(cmd_sql);
            stm.setString(1, nom);
            ResultSet rslt = stm.executeQuery();

            for (int i = 0; rslt.next(); i++) {
                String row[] = {rslt.getString(1), rslt.getString(2), rslt.getString(3), rslt.getString(4)};
                model.addRow(row);
            }
            tablePesanan.setModel(model);

        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_belumBayarActionPerformed

    private void pesananTermehongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesananTermehongActionPerformed
        // TODO add your handling code here:
        nom = nomor.getText();

        model.setRowCount(0);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection cnc = DriverManager.getConnection("jdbc:mysql://localhost:3306/uas", "root", "");
            String cmd_sql = "SELECT id_pesanan, buku.nama_buku, status, harga_pesanan FROM pesanan INNER JOIN buku ON pesanan.id_buku = buku.id_buku WHERE harga_pesanan = (SELECT MAX(harga_pesanan) FROM pesanan);";
            PreparedStatement stm = cnc.prepareStatement(cmd_sql);
            ResultSet rslt = stm.executeQuery();

            for (int i = 0; rslt.next(); i++) {
                String row[] = {rslt.getString(1), rslt.getString(2), rslt.getString(3), rslt.getString(4)};
                model.addRow(row);
            }
            tablePesanan.setModel(model);

        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_pesananTermehongActionPerformed

    private void hapusPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPesananActionPerformed
        // TODO add your handling code here:

        int barisPilih = tablePesanan.getSelectedRow();

        String idPsn = model.getValueAt(barisPilih, 0).toString();

        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection cnc = DriverManager.getConnection("jdbc:mysql://localhost:3306/uas", "root", "");
            String cmd_sql = "DELETE FROM pesanan WHERE id_pesanan = ?";
            PreparedStatement stm = cnc.prepareStatement(cmd_sql);
            stm.setString(1, idPsn);
            int rslt = stm.executeUpdate();

            if(rslt != 0){
                JOptionPane.showMessageDialog(this, "Berhasil membatalkan pesanan", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
                model.setRowCount(0);
            } else {
                JOptionPane.showMessageDialog(null, "Tidak valid!");
            }
            cnc.close();

        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }

        tampilPesanan(nom);
    }//GEN-LAST:event_hapusPesananActionPerformed

    private void pilihBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihBActionPerformed
        // TODO add your handling code here:
        String pilihBank = pilihB.getSelectedItem().toString();
        
        if(pilihBank == "Bank Mandiri"){
            rekBank.setText("177089456");
        }else if (pilihBank == "Bank BNI"){
            rekBank.setText("8756234");
        }else if(pilihBank == "Bank BRI"){
            rekBank.setText("56251839");
        }else if(pilihBank == "Bank BCA"){
            rekBank.setText("988654275");
        } else {
            rekBank.setText("Gada");
        }
    }//GEN-LAST:event_pilihBActionPerformed

    private void tablePesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePesananMouseClicked
        // TODO add your handling code here:
        model = (DefaultTableModel) tablePesanan.getModel();
        cellBaris = tablePesanan.getSelectedRow();
        
        kodPes.setText(model.getValueAt(cellBaris, 0).toString());
    }//GEN-LAST:event_tablePesananMouseClicked

    private void kPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kPembayaranActionPerformed
        // TODO add your handling code here:
        String kodePesan = kodPes.getText();
        String rekeningB = rekBank.getText();
        if(rekeningB.isEmpty() || kodePesan.isEmpty()){
            JOptionPane.showMessageDialog(this, "Pilih buku dan metode pembayaran", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            try{
                Class.forName("com.mysql.jdbc.Driver");
                Connection cnc = DriverManager.getConnection("jdbc:mysql://localhost:3306/uas", "root", "");
                String cmd_sql = "UPDATE pesanan SET status = \"Telah dibayar\" WHERE id_pesanan = ?";
                PreparedStatement stm = cnc.prepareStatement(cmd_sql);
                stm.setString(1, kodePesan);
                
                int rslt = stm.executeUpdate();
                
                
                if(rslt > 0){
                    JOptionPane.showMessageDialog(this, "Berhasil di merubah jumlah dari keranjang", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
                    model.setRowCount(0);
                    
                    tampilPesanan(nom);
                } else {
                    JOptionPane.showMessageDialog(null, "Tidak valid!");
                    kodPes.setText("");
                    rekBank.setText("");
                }
                cnc.close();
                
            } catch (Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_kPembayaranActionPerformed

    private void pesananTermurahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesananTermurahActionPerformed
        // TODO add your handling code here:
        nom = nomor.getText();

        model.setRowCount(0);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection cnc = DriverManager.getConnection("jdbc:mysql://localhost:3306/uas", "root", "");
            String cmd_sql = "SELECT id_pesanan, buku.nama_buku, status, harga_pesanan FROM pesanan INNER JOIN buku ON pesanan.id_buku = buku.id_buku WHERE harga_pesanan = (SELECT MIN(harga_pesanan) FROM pesanan);";
            PreparedStatement stm = cnc.prepareStatement(cmd_sql);
            ResultSet rslt = stm.executeQuery();

            for (int i = 0; rslt.next(); i++) {
                String row[] = {rslt.getString(1), rslt.getString(2), rslt.getString(3), rslt.getString(4)};
                model.addRow(row);
            }
            tablePesanan.setModel(model);

        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_pesananTermurahActionPerformed

    public void tampilPesanan(String nomP){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection cnc = DriverManager.getConnection("jdbc:mysql://localhost:3306/uas", "root", "");
            String cmd_sql = "SELECT id_pesanan, buku.nama_buku, status, harga_pesanan FROM pesanan INNER JOIN buku ON pesanan.id_buku = buku.id_buku WHERE id_keranjang = ?;";
            PreparedStatement stm = cnc.prepareStatement(cmd_sql);
            stm.setString(1, nomP);
            ResultSet rslt = stm.executeQuery();

            for (int i = 0; rslt.next(); i++) {
                String row[] = {rslt.getString(1), rslt.getString(2), rslt.getString(3), rslt.getString(4)};
                model.addRow(row);
            }
            tablePesanan.setModel(model);

        } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesanan().setVisible(true);
            }
        });
    }
    
    private void pesananNih(){
        tablePesanan.setRowHeight(30);
        tablePesanan.setGridColor(Color.decode("#FF8833"));
        tablePesanan.setShowGrid(true);
        tablePesanan.setBackground(Color.WHITE);
        tablePesanan.setSelectionBackground(Color.decode("#FFDFAB"));
        tablePesanan.getTableHeader().setBackground(Color.decode("#FC2803"));
        tablePesanan.getTableHeader().setBackground(Color.red);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton belumBayar;
    private javax.swing.JButton hapusPesanan;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kPembayaran;
    private javax.swing.JTextField kodPes;
    public javax.swing.JTextField nomor;
    private javax.swing.JButton pesananTermehong;
    private javax.swing.JButton pesananTermurah;
    private javax.swing.JComboBox<String> pilihB;
    private javax.swing.JTextField rekBank;
    private javax.swing.JTable tablePesanan;
    // End of variables declaration//GEN-END:variables
}
